### PR TITLE
fix is_ssl_handshake

### PR DESCRIPTION
**Pull request by spaceone**
* time consuming if buffer contains 1GB data
* IndexError with empty buffer

### CODE REVIEW

**Comment by spaceone** [comment]
btw. can we move the function somewhere else? e.g. circuits.utils / circuits.net.socket / etc. ?

**Comment by prologic** [comment]
+1 Let's move ``is_ssl_handshake`` to ``circuits.net.utils``?

**Comment by spaceone** [comment]
yes, changes for this are in 2b4d5949cb874583fec7e51e95f693347f7e60d1
I think i have to create a new PR? (Or is here some functionallity to REOPEN the current)

**Comment by prologic** [comment]
Yeah new PR/branch :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Pull request merged**
