### PR TITLE
Implement DropPrivileges. Closes #46

### LINKED ISSUE #46: drop priviledges
There should be a Component which is able to drop priviledges.
This is neccessary to e.g. listen on port 80 (as root) and then run as a normal user.

### PR DESCRIPTION
**Pull request by prologic**

### CODE REVIEW

**Comment by prologic** [comment]
@spaceone Do we still want to add the ``try/except`` on ```OSError`` in this? If so; where and why? I'm not familiar enough with all the different kinds of errors that *could* be raised :) Also if it fails for any reason what should the behavior be? Log and ignore? If we don't ``try/except`` it'll do that anyway by firing an ``exception()`` event :)

**Comment by spaceone** [comment]
Well, the component is expected to run when you start the process. If dropping privileges fail i would suggest to ```manager.stop()``` (as it is a critical security issue).

**Comment by prologic** [comment]
Agreed; so let's do that. I'll ping this PR when I've updated it :)

**Comment by prologic** [comment]
How about this? (*check commit*)

**Comment by prologic** [comment]
@spaceone Updated this per your suggestion(s) and a bit more :)

**Pull request merged**
