### PR TITLE
add static application security tests

### PR DESCRIPTION
**Pull request by jhulten**
starting with bandit

### CODE REVIEW

**Comment by spaceone** [comment]
bandit is part of `ruff` - so we don't need it explicitly?!

**Comment by spaceone** [comment]
```
$ ruff --select B
warning: `ruff <path>` is deprecated. Use `ruff check <path>` instead.
circuits/app/daemon.py:80:13: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
circuits/app/daemon.py:96:13: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
circuits/app/dropprivileges.py:27:13: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
circuits/app/dropprivileges.py:42:13: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
circuits/core/debugger.py:108:48: B004 [*] Using `hasattr(x, "__call__")` to test if x is callable is unreliable. Use `callable(x)` for consistent results.
circuits/core/handlers.py:125:21: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
circuits/core/manager.py:64:13: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
circuits/core/pollers.py:386:16: B025 try-except block with duplicate exception `OSError`
circuits/io/notify.py:27:5: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
circuits/net/sockets.py:85:5: B028 No explicit `stacklevel` keyword argument found
circuits/protocols/stomp/client.py:30:5: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
circuits/protocols/stomp/client.py:56:25: B006 Do not use mutable data structures for argument defaults
circuits/protocols/stomp/transport.py:12:5: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
circuits/protocols/stomp/transport.py:46:21: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
circuits/protocols/stomp/transport.py:63:13: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
circuits/protocols/websocket.py:33:40: B008 Do not perform function call `bytearray` in argument defaults; instead, perform the call within the function, or read the default from a module-level singleton variable
circuits/tools/__init__.py:24:9: B028 No explicit `stacklevel` keyword argument found
circuits/web/_httpauth.py:110:9: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
circuits/web/parsers/http.py:447:13: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
examples/web/wiki/macros/__init__.py:52:54: B023 Function definition does not bind loop variable `m`
tests/core/test_imports.py:11:16: B011 Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
tests/net/test_tcp.py:83:9: B020 Loop control variable `ipv6` overrides iterable it iterates
tests/net/test_udp.py:28:9: B020 Loop control variable `ipv6` overrides iterable it iterates
tests/web/conftest.py:30:57: B006 Do not use mutable data structures for argument defaults
tests/web/jsonrpclib.py:361:13: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
tests/web/test_basicauth.py:26:16: B011 Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
tests/web/test_core.py:45:16: B011 Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
tests/web/test_core.py:91:16: B011 Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
tests/web/test_core.py:101:16: B011 Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
tests/web/test_core.py:110:16: B011 Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
tests/web/test_digestauth.py:31:16: B011 Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
tests/web/test_exceptions.py:49:16: B011 Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
tests/web/test_exceptions.py:59:16: B011 Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
tests/web/test_exceptions.py:70:16: B011 Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
tests/web/test_exceptions.py:84:16: B011 Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
tests/web/test_exceptions.py:98:16: B011 Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
tests/web/test_null_response.py:18:16: B011 Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
tests/web/test_request_failure.py:23:16: B011 Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
tests/web/test_static.py:29:16: B011 Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
tests/web/test_static.py:53:16: B011 Do not `assert False` (`python -O` removes these calls), raise `AssertionError()`
Found 40 errors.
[*] 1 fixable with the `--fix` option (18 hidden fixes can be enabled with the `--unsafe-fixes` option).

```

enable via:
```diff
diff --git pyproject.toml pyproject.toml
index 096efec2..f62fbf0c 100644
--- pyproject.toml
+++ pyproject.toml
@@ -7,7 +7,7 @@ extend-exclude = ["circuits/web/parsers/multipart.py"]
 [tool.ruff.lint]
 preview = true
 ignore-init-module-imports = true
-select = ["E", "W", "F", "I", "D", "TD"]
+select = ["E", "W", "F", "I", "D", "TD", "B"]
 ignore = [
  "E501",  # line-too-long
  "E203",  # whitespace-before-punctuation
```

**Comment by spaceone** [comment]
```
$ ruff --select S circuits
warning: `ruff <path>` is deprecated. Use `ruff check <path>` instead.
circuits/app/daemon.py:53:9: S101 Use of `assert` detected
circuits/core/bridge.py:12:6: S403 `pickle`, `cPickle`, `dill`, and `shelve` modules are possibly insecure
circuits/core/bridge.py:77:9: S110 `try`-`except`-`pass` detected, consider logging the exception
circuits/core/bridge.py:89:35: S301 `pickle` and modules that wrap it can be unsafe when used to deserialize untrusted data, possible security issue
circuits/core/bridge.py:97:9: S110 `try`-`except`-`pass` detected, consider logging the exception
circuits/core/manager.py:136:9: S101 Use of `assert` detected
circuits/io/process.py:8:6: S404 `subprocess` module is possibly insecure
circuits/io/process.py:63:13: S603 `subprocess` call: check for execution of untrusted input
circuits/net/sockets.py:782:21: S104 Possible binding to all interfaces
circuits/node/server.py:16:31: S104 Possible binding to all interfaces
circuits/protocols/websocket.py:200:41: S311 Standard pseudo-random generators are not suitable for cryptographic purposes
circuits/tools/__init__.py:20:9: S110 `try`-`except`-`pass` detected, consider logging the exception
circuits/web/_httpauth.py:94:22: S324 Probable use of insecure hash functions in `hashlib`: `md5`
circuits/web/_httpauth.py:95:27: S324 Probable use of insecure hash functions in `hashlib`: `md5`
circuits/web/_httpauth.py:105:5: S101 Use of `assert` detected
circuits/web/_httpauth.py:120:5: S101 Use of `assert` detected
circuits/web/_httpauth.py:121:5: S101 Use of `assert` detected
circuits/web/_httpauth.py:136:5: S101 Use of `assert` detected
circuits/web/_httpauth.py:207:5: S101 Use of `assert` detected
circuits/web/http.py:89:32: S104 Possible binding to all interfaces
circuits/web/main.py:124:23: S324 Probable use of insecure hash functions in `hashlib`: `md5`
circuits/web/sessions.py:21:12: S324 Probable use of insecure hash functions in `hashlib`: `sha1`
circuits/web/tools.py:227:37: S324 Probable use of insecure hash functions in `hashlib`: `md5`
circuits/web/url.py:77:9: S101 Use of `assert` detected
circuits/web/websockets/client.py:93:36: S311 Standard pseudo-random generators are not suitable for cryptographic purposes
circuits/web/websockets/dispatcher.py:84:22: S324 Probable use of insecure hash functions in `hashlib`: `sha1`
circuits/web/wrappers.py:40:10: S104 Possible binding to all interfaces
Found 27 errors.

```

enable via:
```diff
diff --git pyproject.toml pyproject.toml
index 096efec2..f62fbf0c 100644
--- pyproject.toml
+++ pyproject.toml
@@ -7,7 +7,7 @@ extend-exclude = ["circuits/web/parsers/multipart.py"]
 [tool.ruff.lint]
 preview = true
 ignore-init-module-imports = true
-select = ["E", "W", "F", "I", "D", "TD"]
+select = ["E", "W", "F", "I", "D", "TD", "S"]
 ignore = [
  "E501",  # line-too-long
  "E203",  # whitespace-before-punctuation
```

**Comment by jhulten** [comment]
Interesting. I will take a closer look. the output you presented seems to eat some of the regular output (severity for instance) but I will see if there is more to learn there before moving on this.

**Pull request closed without merging**
