### PR TITLE
web: add "expose_circuits" options in web server

### PR DESCRIPTION
**Pull request by treemo**
In general, security by obscurity is one of the weakest forms of security. But in some cases, every little bit of extra security is desirable.

A few simple techniques can help to hide Circuits details, possibly slowing down an attacker who is attempting to discover weaknesses in your system. By setting expose_circuits to False in your Server constructor, you reduce the amount of information available to them.

### CODE REVIEW

**Comment by spaceone** [comment]
There are a lot techniques to find this things out in circuits.web. Producing a traceback should not be hard which exposes which circuits version this is via line numbers and file pathes.

**Comment by treemo** [comment]
yes, for the debug traceback (500 error), I will like hide in production and redirect to logger (in an other pull request).

**Comment by prologic** [comment]
Ahh This PR gives the user the option to turn off the "Powered by circuits ..."?

**Comment by spaceone** [comment]
well, partly. The intention is to hide internals which provide security relevant information.

**Comment by prologic** [comment]
An example of what's being hidden?

**Comment by spaceone** [comment]
Isn't this obvious? The HTTP server header and the powered by notification.

**Comment by prologic** [comment]
That's what I thought but @spaceone made it sound like something else ☺

**Comment by prologic** [comment]
Turns out enabling Travis CI on circuits has helped a bit :)

See: https://travis-ci.org/circuits/circuits/jobs/62158763

This PR is missing a few things?

**Pull request merged**
