### PR TITLE
make __str__ compatible with py2

### LINKED ISSUE #229: Value.__str__() issues with Unicode
### Expected Behaviour

I expect the Value.\__str__() function to always work, but it doesn't if the value is Unicode and you are running in 2.7.  (Works fine in Python 3)
https://github.com/circuits/circuits/blob/master/circuits/core/values.py#L76

### Steps to reproduce
To get this error:

> UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

Run this:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import logging
from circuits import Event, Component
LOG = logging.getLogger(__name__)

class something(Event):
    def __init__(self, value):
        self.success = True
        super(something, self).__init__(value=value)
        self.saved_value = value
class TestComponent(Component):
    """ test component """
        
    def something(self, event, value):
        LOG.info("Handling value %s for event %s", value, event)
        yield value

    def something_success(self, event, *args):
        LOG.info("Event %s with value %s was successfully handled", event.parent, repr(event.parent.value))
        LOG.info(event.parent.value)
        yield "done"
        
    def started(self, event, *args):
        """ helper that does the first 3 items of work """
        LOG.info("Firing event with Unicode")
        value = u"те яуо еиус дицам е"
        self.fire(something(value))

def main():
    logging.basicConfig()
    LOG.setLevel(logging.DEBUG)
    TestComponent().run()
    
if __name__ == "__main__":
    main()
```

### Environment and Platform

- OS: Mac OS
- Python: 2.7
- circuits: 3.2

----

### PR DESCRIPTION
**Pull request by bloodywing**
See a similar implementation in six:
https://github.com/circuits/circuits/blob/master/circuits/six.py#L840

Do we want to use the decorator and add `__unicode__`?

Fixes #229

### CODE REVIEW

**Comment by prologic** [comment]
@spaceone What do you think?

**Comment by bloodywing** [comment]
@prologic after looking into six a bit more I realized that the best approach would be the decorator `@python_2_unicode_compatible`. The same method is used in Django: https://github.com/django/django/blob/1.10/django/db/models/manager.py#L12 for a long time now, which also makes this more familiar to people.
And it's cleaner to maintain, if circuits should ever ditch PY2 support one day.

**Comment by prologic** [comment]
Go fer it! :D


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by prologic** [comment]
Can you fix the conflicts?

**Comment by bloodywing** [comment]
@prologic Was this more of an issue with your travis config?

**Comment by prologic** [comment]
Just some bad racey tests :/ circuits has more e2e tests than actual unit
tests :/


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Pull request merged**
