### PR TITLE
Implement Component.__nonzero__ so components have the same thruthy values as normal objects. Fixes #51

### LINKED ISSUE #51: Implement Component.__nonzero__ proper
BaseComponent/Manager implements __bool__/__nonzero__ which returns True if there are pending events.
As it is a API to inherit from BaseComponent this is error prone.
I needed a lot time to debug the lines:
```
if arg:
    foo()
```
which failed but worked finally with ```if arg is not None:``` (where arg is a component, e.g. event.value.manager).

We should not overwrite pythons expected default behavior in the API and instead hide internals like those.

### PR DESCRIPTION
**Pull request by prologic**
Fixes #51

### CODE REVIEW

**Comment by spaceone** [comment]
Yes, this seems great!
I think python3 renamed ```__nonzero__``` to ```__bool__``` → so that method have to be implemented, too?

**Comment by prologic** [comment]
Can you confirm? We can just alias it if so.

**Comment by spaceone** [comment]
Yes, it is as i said:
Just add the line ```__bool__ = __nonzero__````in manager.py

```
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> class Foo(object):
...     def __len__(self):
...         return 0
...     def __nonzero__(self):
...         return True
... 
>>> f = Foo()
>>> bool(f)
False
>>> class Foo(object):
...     def __len__(self):
...         return 0
...     def __bool__(self):
...         return True
... 
>>> f = Foo()
>>> bool(f)
True
```

**Comment by prologic** [comment]
:+1:

**Pull request merged**
