### PR TITLE
trying to fix test cases

### PR DESCRIPTION
**Pull request by spaceone**
let's see what the test cases say...

### CODE REVIEW

**Comment by prologic** [comment]
Haha :) ``tox`` doesn't work for you locally? :)

**Comment by spaceone** [comment]
I cannot setup pytest properly...Also I only have py2.7.

**Comment by prologic** [comment]
I'll have to help you set that up properly ;0 I normally develop on Python 2.7 too I do have Python 2.6, 2.7, 3.2., 3.3, 3.4, 3.5 and pypy all installed locally :)

**Comment by prologic** [comment]
Looks like this fixed all the errors.

**Comment by prologic** [comment]
Oh oh oh oh! :) You can't set ``self.parent = self`` here because the deregistration hasn't been completed yet :)

**Comment by spaceone** [comment]
yes... but this was IMHO a error in the test cases not in the code... We have to reset parent and root on unregistering.

**Comment by prologic** [comment]
This is already handled in [L199](https://github.com/circuits/circuits/blob/master/circuits/core/components.py#L199)

**Comment by spaceone** [comment]
Ok, but this does not work without `tick()`

**Comment by prologic** [comment]
What do you mean?

**Comment by spaceone** [comment]
If the unregistering is done while the component does not `run()` the .parent and .root is wrong. Probably that's okay, but it looked weird in a interactive python shell.

**Comment by prologic** [comment]
Ahh yes I see what you mean. Unfortunately I don't think there's an easy answer to this! registration and deregistration are not designed to be static things. They both fire off events so that they can be intercepted and something useful done with them :)

**Comment by spaceone** [comment]
okay ;)

**Comment by prologic** [comment]
So we're all good then :+1:  I'll merge this in to fix the broken assumption :)

**Comment by spaceone** [comment]
one test case fails: https://travis-ci.org/circuits/circuits/jobs/66493853 → how does this come?

**Comment by prologic** [comment]
Merged.

**Comment by prologic** [comment]
I haven't been able to fix the unreliable nature of these two tests (*especialyl for PyPy*):

* [ ] https://github.com/circuits/circuits/blob/master/tests/core/test_worker_thread.py
* [ ] https://github.com/circuits/circuits/blob/master/tests/core/test_bridge.py

**Pull request closed without merging**
