### PR TITLE
Adapt reprhandler(): include priority, join with ,

### PR DESCRIPTION
**Pull request by spaceone**
before: ```<handler[channel.event1.event2] (Foo._on_event1_2)>```
After: ``` <handler[channel][event1,event2][1.3] (Foo._on_event1_2)>```

### CODE REVIEW

**Comment by prologic** [comment]
:+1:

**Comment by prologic** [comment]
Really nice patch :)

**Comment by spaceone** [comment]
Is the channel important? we could move it to the second [] block

**Comment by prologic** [comment]
I think it's fine the way you've improved it. The ``channel`` is kind f important for debugging as you can and will typically have multiple similar components or entire component graphs on different channels :)

**Pull request merged**
