### PR TITLE
Shink sdist even further. Fixes #110

### LINKED ISSUE #110: Shrinking the circuits sdist even more...
See: #78 #78 #108 and #109 

I believe there's room to improve on this be removing a fews other things that are generally not needed in a source distributions and are only really useful to developers (*who will typically clone the repository via ``git``*0:

- Let's not ship docs at all
- Let's not ship the fabfile tasks
- Let's not ship the examples

This brings us down to ~250KB package.

### PR DESCRIPTION
**Pull request by prologic**

### CODE REVIEW

**Comment by prologic** [comment]
Bump; anyone see any issues with this?

**Comment by prologic** [comment]
@eriol ping? :)

**Comment by eriol** [comment]
Thanks for pinging me! :)

LGTM!

I looked at the installation data provided by popularity-contest both on Debian and Ubuntu and, although this data can not be taken as a scientific source, documentation package is installed very few times.

For example on Ubuntu:

Package | Installed | Source
-----------|------------|---------
python-circuits| > 140 | http://ubuntu-popcon.43-1.org/cgi-bin/graph.pl?name=python-circuits
python-circuits-doc| < 10 | http://ubuntu-popcon.43-1.org/cgi-bin/graph.pl?name=python-circuits-doc

Since Read the Docs is so good, I think that not shipping docs in source dist is fine. If someone will open a bug about the missing docs we can reconsider this choice! :smile:

**Comment by prologic** [comment]
:+1: Wonderful! I'll merge this; this morning :)

**Pull request merged**
