### PR TITLE
Fix __sub__; Issue 93

### PR DESCRIPTION
**Pull request by spaceone**

### CODE REVIEW

**Comment by prologic** [comment]
I think you need to rebase this :)

Also ``Fixes #93`` in the commit :)

**Comment by spaceone** [comment]
done

**Comment by prologic** [comment]
Whoops! This broke a bunch of stuff!

https://travis-ci.org/circuits/circuits/builds/66487372

I should have waited for the Travis CI report back before merging!

@spaceone Want to investigate this one?

**Comment by spaceone** [comment]
It is probably the line ```self.parent = self``` in unregister()... Well, are the test definitions wrong?

**Comment by prologic** [comment]
```#!python
>>> from circuits import Component
>>> x = Component()
>>> x.parent is x
True
>>> x.root is x
True
```

Yes possibly :)

**Pull request merged**
