### PR TITLE
Improved Bridge (more inline with how node works)

### PR DESCRIPTION
**Pull request by prologic**

### CODE REVIEW

**Comment by prologic** [comment]
This changes the Bridge usage a bit:

* Removes implicit event traversal.
* Events are now explicitly sent to a subprocess.

**Usage:**

```#!python
from __future__ import print_function

from os import getpid


from circuits import child, Event, Component


class hello(Event):
    """hello Event"""


class Child(Component):

    def hello(self):
        return "Hello from child with pid {0}".format(getpid())


class App(Component):

    def init(self):
        Child().start(process=True, link=self)

    def ready(self, *args):
        x = yield self.call(hello())
        yield print(x)

        y = yield self.call(child(hello()))
        yield print(y)

        raise SystemExit(0)

    def hello(self):
        return "Hello from parent with pid {0}".format(getpid())


App().run()
```

**Output:**
```#!bash
$ python test_bridge.py
Hello from parent with pid 814
Hello from child with pid 817
```

**Comment by prologic** [comment]
This also works with multiple subprocesses:

**Example:**

```#!python
from __future__ import print_function

from os import getpid


from circuits import child, Event, Component


class go(Event):
    """go Event"""


class hello(Event):
    """hello Event"""


class Child(Component):

    def hello(self):
        return "Hello from child with pid {0}".format(getpid())


class App(Component):

    def init(self):
        self.counter = 0
        self.child1 = Child().start(process=True, link=self)
        self.child2 = Child().start(process=True, link=self)

    def ready(self, *args):
        self.counter += 1
        if self.counter < 2:
            return
        self.fire(go())

    def go(self):
        x = yield self.call(hello())
        yield print(x)

        y = yield self.call(child(hello()), self.child1[1].channel)
        yield print(y)

        z = yield self.call(child(hello()), self.child2[1].channel)
        yield print(z)

        raise SystemExit(0)

    def hello(self):
        return "Hello from parent with pid {0}".format(getpid())


App().run()
```

**Output:**

```#!bash
$ python examples/hello_bridge.py
Hello from parent with pid 1733
Hello from child with pid 1736
Hello from child with pid 1737
```

**Comment by prologic** [comment]
bump!

**Comment by prologic** [comment]
I want to get this merged in pretty quckly so speak y'all :) I have a use-case for this improved bridge in oss6/statico#12

**Comment by treemo** [comment]
@prologic I never use the bridge (I use node for dispatch the events on process / host)

**Comment by prologic** [comment]
@treemo Yeah that's cool! I tried to modify the bridge such that it has a very similar API and usage to Node :) What do you think anyway?

**Comment by spaceone** [comment]
I'll give my feedback in the evening (in german time zone).

**Comment by spaceone** [comment]
I think the change is really nice, i like explicity... But I don't like the event name `child`. I currently can't think of which name suits better.

**Comment by prologic** [comment]
The *reason* I called it ``child()`` was the following connotations:

* Let's fire a remote event foo to host:port
* Let's fire a child event foo to uuid

**Comment by prologic** [comment]
@all Okay so we *could* call the event ``ipc()`` if that makes more sense?

Was just thinking about this; you could also message the parent, not just the child. For example in [pingpong.py](https://github.com/circuits/circuits/blob/improved-bridge/examples/pingpong.py)

**Comment by prologic** [comment]
Bump :)

Also see: https://gist.github.com/prologic/7bb5bbcecfb79bfdc841

Just playing around here... Could turn into something more concrete!

**Comment by prologic** [comment]
bump

**Comment by prologic** [comment]
I'm going to rename the event to ``ipc()`` and merge this!

**Pull request closed without merging**
