### PR TITLE
Fix for circuits/circuits#135.

### PR DESCRIPTION
**Pull request by mnlipp**
As discussed in circuits/circuits#135. (Finally found some time to set things up properly.)

### CODE REVIEW

**Comment by prologic** [comment]
So there's a bunch of tests that have failed. Would you mind running (*if you can*) ``tox`` locally or just ``python setup.py test`` to see if you've broken anything? :)

**Comment by mnlipp** [comment]
I can try tomorrow (too late here now). But the circuits 3.2 builds were already failing before my pull request. So I assume that my 3.1 branch will run as fine with my patch as it did without. But I will check.

**Comment by spaceone** [comment]
no, there are more failing tests.

**Comment by prologic** [comment]
Yeah we have Travis test against all supported version of Python -- There are quite a few failing right now -- If you can have a look tomorrow that would be good :)

**Comment by mnlipp** [comment]
Seems that nothing appears here automatically. I've updated the fix yesterday. The checks that still fail are those that already failed in the 3.1 base.

**Comment by mnlipp** [comment]
Thought about that. My focus was on getting my circuits-3.1 based app running, so I sought for a minimal change. Feel free to fix the bug in another way for "master".

**Comment by prologic** [comment]
I'll take a look hopefully tonight :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by spaceone** [comment]
Fixed in
https://github.com/circuits/circuits/commit/6469ae60f00ec5d0de84b282a654b89b94b69666
https://github.com/circuits/circuits/commit/211cc25e758cb93e6ccefada4f50bb3971010244

**Comment by prologic** [comment]
Thanks @spaceone :+1:

**Pull request closed without merging**
